# Generated by Django 3.2.4 on 2021-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_tag'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceTag',
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='common.Tag', verbose_name='Теги'),
        ),
    ]
