# Generated by Django 3.2.4 on 2021-07-09 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210630_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Возраст'),
        ),
    ]
