# Generated by Django 3.2.4 on 2021-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_alter_tag_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ на вопрос')),
                ('pubDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('chosen', models.BooleanField(default=False, verbose_name='Выбор наставника')),
                ('tags', models.ManyToManyField(related_name='questions', to='common.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['pubDate'],
            },
        ),
    ]
