version: '3'

services:
    backend:
        build:
            context: ./backend
        command: gunicorn BBBS_project.wsgi -- bind 0.0.0.0:8000
        ports:
            - "8000:8000"
    frontend:
        build:
            context: ./frontend
        volumes:
            - react_build:/fronted/build
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.bb_bs_project/default.conf:ro
            - react_build:/var/www/frontend
        depends_on:
            - backend
            - frontend
volumes:
    react_build: