# Generated by Django 3.2.4 on 2021-06-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210604_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='is_primary',
            new_name='isPrimary',
        ),
    ]
