# Generated by Django 3.2.4 on 2021-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210608_2016'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user', 'city'), name='Profile value unique'),
        ),
    ]
