# Generated by Django 3.2.4 on 2021-06-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_user_role'),
        ('common', '0004_tag'),
    ]

    operations = [
    ]
