# Generated by Django 3.2.4 on 2021-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_merge_0004_alter_user_role_0004_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='model',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('place', 'Place'), ('rights', 'Rights'), ('questions', 'Questions')], default='event', max_length=50, verbose_name='Тег для:'),
        ),
    ]
