# Generated by Django 3.2.4 on 2021-06-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique profile',
        ),
    ]
