# Generated by Django 3.2.4 on 2021-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_tag'),
        ('rights', '0002_auto_20210622_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag_Right',
        ),
        migrations.AlterField(
            model_name='right',
            name='tags',
            field=models.ManyToManyField(to='common.Tag', verbose_name='Теги'),
        ),
    ]
