# Generated by Django 3.0.5 on 2021-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ManyToManyField(related_name='profile', to='cities.City', verbose_name='город'),
        ),
    ]
