# Generated by Django 3.2.4 on 2021-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name_plural': 'participates'},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('city', 'start_at', 'title'), name='unique event'),
        ),
    ]
