# Generated by Django 3.2.4 on 2021-07-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0005_auto_20210630_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
    ]
