# Generated by Django 3.2.4 on 2021-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='tag',
        ),
        migrations.AddField(
            model_name='right',
            name='tags',
            field=models.ManyToManyField(to='rights.Tag_Right', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='right',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='right',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='right',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='right',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='right',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
